name: "Change Directory Permissions"
description: "Change permissions and ownership of a directory"

inputs:
  host:
    description: "SSH Host"
    required: true
  username:
    description: "SSH Username"
    required: true
  key:
    description: "SSH Key"
    required: true
  port:
    description: "SSH Port"
    required: true

runs:
  using: "composite"
  steps:
    - name: Change directory permissions
      shell: bash
      run: |
        echo "${{ inputs.key }}" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key
        ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key -p ${{ inputs.port }} ${{ inputs.username }}@${{ inputs.host }} <<'EOF'
          if [ -d /home/${{ inputs.username }}/Crystall/ ]; then
            sudo chmod -R 777 /home/${{ inputs.username }}/Crystall/ && echo "chmod done"
            sudo chown -R ${{ inputs.username }}:${{ inputs.username }} /home/${{ inputs.username }}/Crystall/ && echo "chown done"
          else
            echo "/home/${{ inputs.username }}/Crystall/ not found"
          fi
        EOF
