"""UserRole FK Roles.Name

Revision ID: 0440de1187b8
Revises: 390cf7410d7e
Create Date: 2024-02-06 21:08:26.816731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0440de1187b8'
down_revision: Union[str, None] = '390cf7410d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Roles', ['name'])
    op.add_column('Users', sa.Column('role', sa.String(), nullable=True))
    op.drop_constraint('Users_role_id_fkey', 'Users', type_='foreignkey')
    op.create_foreign_key(None, 'Users', 'Roles', ['role'], ['name'])
    op.drop_column('Users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.create_foreign_key('Users_role_id_fkey', 'Users', 'Roles', ['role_id'], ['id'])
    op.drop_column('Users', 'role')
    op.drop_constraint(None, 'Roles', type_='unique')
    # ### end Alembic commands ###
