"""group

Revision ID: bc559329b022
Revises: 4fe8452e0448
Create Date: 2024-04-10 13:40:51.839147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc559329b022'
down_revision: Union[str, None] = '4fe8452e0448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Groups', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Groups', 'deleted')
    # ### end Alembic commands ###
