"""group

Revision ID: 63443abb7b71
Revises: fdafdc487a17
Create Date: 2024-04-10 14:12:43.996147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63443abb7b71'
down_revision: Union[str, None] = 'fdafdc487a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Groups', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Groups', type_='unique')
    # ### end Alembic commands ###
