"""add relation

Revision ID: 71be83203689
Revises: 40bb5fc86738
Create Date: 2024-10-12 19:26:01.007091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71be83203689'
down_revision: Union[str, None] = '40bb5fc86738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_constraint_extended_dataset", 'ExtendedDataset', ['id'])
    op.add_column('Users', sa.Column('extended_id', sa.Integer(), nullable=True))
    op.create_foreign_key("foreign_key_users_extended_dataset", 'Users', 'ExtendedDataset', ['extended_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("foreign_key_users_extended_dataset", 'Users', type_='foreignkey')
    op.drop_column('Users', 'extended_id')
    op.drop_constraint("unique_constraint_extended_dataset", 'ExtendedDataset', type_='unique')
    # ### end Alembic commands ###
