"""group

Revision ID: 33607fe75b34
Revises: 63443abb7b71
Create Date: 2024-04-10 14:16:00.541162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33607fe75b34'
down_revision: Union[str, None] = '63443abb7b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Groups_name_key', 'Groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Groups_name_key', 'Groups', ['name'])
    # ### end Alembic commands ###
