"""Create avatar row

Revision ID: 9a2e8912850c
Revises: f65245fdbb2d
Create Date: 2024-06-14 22:02:49.898699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2e8912850c'
down_revision: Union[str, None] = 'f65245fdbb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('avatar', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'avatar')
    # ### end Alembic commands ###
