"""Add Training level

Revision ID: 65bfd6911a75
Revises: ca7fdd1115df
Create Date: 2024-07-03 16:01:04.178377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bfd6911a75'
down_revision: Union[str, None] = 'ca7fdd1115df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrainingLevels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=35), nullable=False),
    sa.Column('date_add', sa.DateTime(), nullable=False),
    sa.Column('date_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('Trainings', sa.Column('level_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Trainings', 'TrainingLevels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Trainings', type_='foreignkey')
    op.drop_column('Trainings', 'level_id')
    op.drop_table('TrainingLevels')
    # ### end Alembic commands ###
