"""Fix photo

Revision ID: bc27348192dd
Revises: 938f10f7bc61
Create Date: 2024-09-02 10:15:17.265930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc27348192dd'
down_revision: Union[str, None] = '938f10f7bc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Notifications', ['id'])
    op.alter_column('Users', 'photo',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'photo',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.drop_constraint(None, 'Notifications', type_='unique')
    # ### end Alembic commands ###
