"""Add Status and Awards

Revision ID: 4757f4bc5fc5
Revises: bc27348192dd
Create Date: 2024-09-04 15:48:33.682346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4757f4bc5fc5'
down_revision: Union[str, None] = 'bc27348192dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
# Define the enum type
status_type_enum = sa.Enum('created', 'in_progress', 'completed', name='status_type_enum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Awards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('Checks', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('Checks', sa.Column('awards', sa.Integer(), nullable=True))
    op.create_foreign_key("check_award_constraint", 'Checks', 'Awards', ['awards'], ['id'])

    status_type_enum.create(op.get_bind())
    op.add_column('Lessons', sa.Column('status', sa.Enum('created', 'in_editing', 'in_progress', 'finished', name='status_type_enum'), server_default='created', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Lessons', 'status')
    status_type_enum.drop(op.get_bind())
    op.drop_constraint("check_award_constraint", 'Checks', type_='foreignkey')
    op.drop_column('Checks', 'awards')
    op.drop_column('Checks', 'comment')
    op.drop_table('Awards')
    # ### end Alembic commands ###
