"""Check fix

Revision ID: ca7fdd1115df
Revises: 9a2e8912850c
Create Date: 2024-07-03 11:41:33.095233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7fdd1115df'
down_revision: Union[str, None] = '9a2e8912850c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Checks_lesson_id_fkey', 'Checks', type_='foreignkey')
    op.create_foreign_key(None, 'Checks', 'Lessons', ['lesson_id'], ['id'])
    op.alter_column('TrainingChecks', 'repetitions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('TrainingChecks', 'assessment',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TrainingChecks', 'assessment',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('TrainingChecks', 'repetitions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'Checks', type_='foreignkey')
    op.create_foreign_key('Checks_lesson_id_fkey', 'Checks', 'Users', ['lesson_id'], ['id'])
    # ### end Alembic commands ###
