"""IsMan -> default=True

Revision ID: 390cf7410d7e
Revises: 8c59120d1a66
Create Date: 2024-02-05 19:48:17.278475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390cf7410d7e'
down_revision: Union[str, None] = '8c59120d1a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Groups', 'Users', ['trainer_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Groups', type_='foreignkey')
    # ### end Alembic commands ###
