"""relation fix

Revision ID: 651274dd6568
Revises: 0440de1187b8
Create Date: 2024-02-10 20:26:55.364369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651274dd6568'
down_revision: Union[str, None] = '0440de1187b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Users', 'Groups', ['group_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'group_id')
    # ### end Alembic commands ###
