"""Add verification code by DB

Revision ID: 8065387426a0
Revises: 36710f8c8464
Create Date: 2023-10-17 17:26:59.634481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8065387426a0'
down_revision: Union[str, None] = '36710f8c8464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'code')
    # ### end Alembic commands ###
