"""Chenge user model

Revision ID: 8f9bf853da53
Revises: 6d6f531b2cfd
Create Date: 2023-10-12 14:59:25.210972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9bf853da53'
down_revision: Union[str, None] = '6d6f531b2cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'user_group', 'user', ['trainer_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group', type_='foreignkey')
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
